catchpoint:
  apikey: <QA-API-KEY>
  application:
    name: user-service
    classname: Tornado
  report:
    rest:
      baseurl: https://collector-qa.tracing.catchpoint.net/v1/
  trace:
    instrument:
      traceableconfig1: com.catchpoint.tracing.demo.todo.controller.*.*[traceLineByLine=true]
      traceableconfig2: com.catchpoint.tracing.demo.todo.service.*.*[traceLineByLine=true]
