catchpoint:
  apikey: a07edb98-37ac-4ba3-ba59-050681495361
  application:
    name: todo-service
  report:
    rest:
      baseurl: https://collector-staging.tracing.catchpoint.net/v1/
  trace:
    instrument:
      traceableconfig1: com.catchpoint.tracing.demo.todo.controller.*.*[traceLineByLine=true]
      traceableconfig2: com.catchpoint.tracing.demo.todo.service.*.*[traceLineByLine=true]
