catchpoint:
  apikey: 6d74ff0d-ebb4-48a9-b0ff-4d1112d7b489
  application:
    name: todo-service
  report:
    rest:
      baseurl: https://collector.tracing.catchpoint.com/v1/
  trace:
    instrument:
      traceableconfig1: com.catchpoint.tracing.demo.todo.controller.*.*[traceLineByLine=true]
      traceableconfig2: com.catchpoint.tracing.demo.todo.service.*.*[traceLineByLine=true]
