thundra:
  apikey: <STAGING-API-KEY>
  agent:
    application:
      name: todo-service
    report:
      rest:
        baseurl: https://collector-staging.tracing.catchpoint.net/v1/
    trace:
      instrument:
        traceableconfig1: com.catchpoint.tracing.demo.todo.controller.*.*[traceLineByLine=true]
        traceableconfig2: com.catchpoint.tracing.demo.todo.service.*.*[traceLineByLine=true]
