spring:
  application:
    name: todo-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:todo-db
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  schedule:
    enabled: true
server:
  port: 5000
chaos:
  enabled: true
user:
  check:
    enabled: true
